language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.9; fi

matrix:
  include:
  - node_js: '9'
    os: linux
    env: [NSP=true]
  - node_js: '8'
    os: linux
    env: [NSP=true]
  - node_js: '6'
    os: linux
    env: [NSP=true]
  - node_js: '4'
    os: linux
  - node_js: '9'
    os: osx
    env: [NSP=true]
  - node_js: '8'
    os: osx
    env: [NSP=true]
  - node_js: '6'
    os: osx
    env: [NSP=true]
  - node_js: '4'
    os: osx

script:
  - npm run test
  - if [[ $NSP ]]; then npm run audit; else echo "skip audit"; fi
